-- =============================================================================
--  DATOS INICIALES  ·  ejecutar DESPUÉS de 01_schema.sql
--  Fuentes: O-19b Código de proveedores, NUEVOS CODIGOS (pdf), NUEVOS_CODIGOS_QUE_SE_AUMENTO.xlsx
--  Catálogo CONFIRMADO por la bodega el 07/09/2026 (HUP hueso pollo incluido).
-- =============================================================================

insert into especies (codigo, nombre) values
  ('R', 'Res'),
  ('C', 'Cerdo'),
  ('P', 'Pollo'),
  ('V', 'Vísceras'),
  ('B', 'Borrego'),
  ('I', 'Importado'),
  ('PV', 'Pavo'),
  ('T', 'Ternera'),
  ('M', 'Mariscos'),
  ('O', 'Otros');

insert into tipos_proceso (codigo, nombre) values
  ('LIMPIEZA', 'Limpieza / desposte'),
  ('MOLIENDA', 'Molienda'),
  ('FILETEADA', 'Fileteada'),
  ('ACUMULACION', 'Acumulación de subproductos');

insert into proveedores (codigo, nombre, activo) values
  (1, 'ZOILA VILLARES', true),
  (2, 'ERICA FERRIN (Luis CuelL', true),
  (3, 'DUGLAR CASTRO', true),
  (4, 'Ramiro Cuenca', true),
  (5, 'WILLIAM BUENAÑO', true),
  (6, 'DIEGO MORETA', true),
  (7, 'MORALES DORIS', true),
  (8, 'GERMAN CASA', true),
  (9, 'NILO ORBE', true),
  (10, 'MARCO ORBE', true),
  (11, 'CARLOS CAYO', true),
  (12, 'DIEGO CARUA', true),
  (13, 'PAULINA CARUA', true),
  (14, 'XIMENA CHICAIZA', true),
  (15, 'JANETH MATABAY', true),
  (16, 'ROSA LUJE', true),
  (17, 'JUAN SANCHEZ', true),
  (18, 'MONICA CASA', true),
  (19, 'SILVANA QUINTANILLA', true),
  (20, 'TITAN', true),
  (21, 'PRONACA', true),
  (22, 'MORETA DANIEL', true),
  (23, 'FANNY CANDO', true),
  (24, 'PLANTA PRODUCCION', true),
  (25, 'MARCELO ANDRADE', true),
  (26, 'ROLANDO BURBANO', true),
  (27, 'KARINA ESPINOZA', true),
  (28, 'JOEL SARABIA', true),
  (29, 'GUALOTO NELY', true),
  (30, 'JORGE VISCAINO', true),
  (31, 'MARCO VILLA', true),
  (32, 'JOEL VEGA ( patas res)', true),
  (33, 'PATRICIA CHANGOLUISA', true),
  (34, 'MARIBEL LOPEZ', true),
  (35, 'REYES GENARO', true),
  (36, 'SILVIA CASTELLANO', true),
  (37, 'AVITALSAPOLLO ANDINO', true),
  (38, 'UNIMARK LEIDI GRANDA', true),
  (39, 'CARNEVOROS (DANIEL GRANDA)', true),
  (40, 'TOCOMRUP', true),
  (41, 'RICARDO GAVELA', true),
  (42, 'NOVA METS', true),
  (43, 'CELESTE _DAVID TORRES', true),
  (44, 'MARCO LUNA', true),
  (45, 'MARCELO LOPEZ', true),
  (46, 'CELI CARPIO', true),
  (47, 'ALEXANDRA LOMBEIDA', true),
  (48, 'JUAN SANCHEZ', true),
  (49, 'DIEGO YANEZ', true),
  (50, 'HUAMAN JULIO', true),
  (51, 'ELSA YANCHAPAXI', true),
  (52, 'LA RANCHERITA', true),
  (53, 'MATABAY MARCO', true),
  (54, 'SEGUNDO VILLA', true),
  (55, 'DIANA SANCHEZ (CARUA)', true),
  (56, 'DIEGO DELGADO', true),
  (57, 'JUAN YUGSI', true),
  (58, 'MIRIAN BENABIDEZ', true),
  (59, 'RIAARDO HINOJOZA', true),
  (60, 'ELIAS ORBE', true),
  (61, 'EDISON QUINTANA', true),
  (62, 'LUIS CUELLAR', true),
  (63, 'DIANA VELEZ', true),
  (64, 'JESUS CALDERON', true),
  (65, 'RODY CHIAN', true),
  (66, 'CARMEN MOREJON patas', true),
  (67, 'WLADIMIR PEREZ', true),
  (68, 'YEREMI PAEZ', true),
  (69, 'LISBETH MALDONADO', true),
  (70, 'LUIS CALO ( Tapia Ximena)', true),
  (71, 'SAUL YAANEZ (BORREGO)', true),
  (72, 'ARTEAGA GUIDO', true),
  (73, 'PIEDADSANTANDER FRESH', true),
  (74, 'HERMANO REYES', true),
  (75, 'EDISON QUINTANILLA', true),
  (76, 'LEILA ECHEVERRIA', true),
  (77, 'HUGO CARRASCO', true),
  (78, 'LA EXQUISITA', true),
  (79, 'ALEXISVILLACIS', true),
  (80, 'PABLO ORTIZ', true),
  (81, 'MARCELOLOPEZ', true),
  (82, 'JENNIFER HERRERA QUESO', true),
  (83, 'HERNESTO', true),
  (84, 'BLANCA ILLAPA', true),
  (85, 'JORGE TUMBACO', true),
  (86, 'CORAL', true),
  (87, 'CRISTINA ALBARRCIN', true),
  (88, 'PEÑAFIEL', true),
  (89, 'LA SELECTA LUIS TUQUERS', true),
  (90, 'QUESO SUR', true),
  (91, 'JOSE SILVA (TRIPA NATUR', true),
  (92, 'FOPROCA TOCINO', true),
  (93, 'KIMBERLY TUPIZA cerdo', true),
  (94, 'FRANCIS AGUIRRE', true),
  (95, 'GORDON MAYORGA', true),
  (96, 'DORIS', true),
  (97, 'DIANA YANCHA', true),
  (98, 'GRUPO ORO', true),
  (99, 'LA PRADERA', true),
  (100, 'TITO CANO', true),
  (101, 'JHONNY MAIGUA', true),
  (102, 'KEVIN SINCHIGUANI', true),
  (103, 'VICTOR YANEZ', true),
  (104, 'NESTOR CRUZ', true),
  (105, 'DIGECA', true),
  (106, 'PAMELA BAQUERIZO', true),
  (107, 'JORDANA SARAAABIA', true),
  (108, 'LEMA LISBETH RES', true),
  (109, 'JUAN CARLOSSINCHIGUANO', true),
  (110, 'GUSTAAVO CUARAN', true),
  (111, 'MUZO JAYANA EMERZON', true),
  (112, 'DIMACSSE MAURIC GAVELA', true),
  (113, 'CRIP POLLO', true),
  (114, 'SIN ASIGNAR', false),
  (115, 'NARVAES CEVALLOS BANES', true),
  (116, 'DISTRISAL', true),
  (117, 'ANGELICA NIEVES DUGLAS', true),
  (118, 'CHAMORRO CARLOS WP', true),
  (119, 'CRISTIAN CAYO', true),
  (120, 'LLAPIN PAAULDIGECA', true),
  (121, 'SUPERMAXI', true),
  (122, 'RENATA PORTILLA', true),
  (123, 'MARIA COLLAAGUASO CAY', true),
  (124, 'LEIBER ALDAZ', true),
  (125, 'PACHECOOLGUER MANTEC', true),
  (126, 'LUIS CONDOR', true),
  (127, 'DISTRIBUIDORA HMEATS PICAÑA Y BIFE BOLIVIANO', true),
  (128, 'NARVAEZ CRISTINA LENGU', true),
  (129, 'BUSTE RIVAS MARIA', true),
  (130, 'JAVIER YANEZ CERDO', true),
  (131, 'SEGUNDO MAIGUA', true),
  (132, 'MANZANO QUINT JOSUE', true),
  (133, 'KELVIN VIRACOCHA', true),
  (134, 'MACAFRI', true),
  (135, 'DISCARVIS SOLEDAD VICERAS', true),
  (136, 'VILLACIS XIMENA gallina ca', true),
  (137, 'NATURASA cerdo', true),
  (138, 'CUMANDA YANEZ borrego', true),
  (139, 'JESUS ALFARO lomo fino', true),
  (140, 'PORTILLA EDGAR salmón', true),
  (141, 'DAVID PANCHI lomo fino', true),
  (142, 'CAYO UNDA GALO Cristian', true),
  (143, 'ULCUANGO GABRIEL', true),
  (144, 'ESPINOZA BRENDA lomo fin', true),
  (145, 'FERNANDO DURAN Ambato', true),
  (146, 'FABIAN QUISHPE lom fin', true),
  (147, 'QUISHPE ANGELICA lomo fino', true),
  (148, 'MARCO LOAIZA', true),
  (149, 'SOFIA SANCHEZ Ambato', true),
  (152, 'BUSTE RIVAS FRANKLIN STALIN', true),
  (154, 'CUEVA ROBYN KEYRO', true),
  (158, 'HEERA FRANKLIN', true),
  (159, 'CUMANRIMA', true),
  (160, 'DISTESA FOOD QUESO', true),
  (161, 'PUCACHI MAGALI viceras', true),
  (162, 'EMILY ORBE', true),
  (165, 'LA SELECTA', true),
  (167, 'DAVID GUANO LISBETH', true),
  (168, 'PAULINA AYAL', true),
  (169, 'FREIRIS', true),
  (170, 'JYMMY CASTRO', true),
  (172, 'DIMACSE', true),
  (173, 'JOSE VALENCIA', true),
  (174, 'AGUSTIN SARABIA JOEL', true),
  (175, 'ACROPROSPERA', true),
  (176, 'NORDICO', true),
  (177, 'CASTILLO EMILIA keyro', true),
  (178, 'EMBUSTER FEDEREG', true);

insert into proveedores (codigo, nombre, notas) values (153, 'REPROAVID', 'Pollo. Agregado por bodega');

insert into productos (codigo, nombre, especie_id, rol_defecto, interno, por_confirmar) values
  ('AB', 'Borrego entero', (select id from especies where codigo='B'), 'principal', false, false),
  ('BB', 'Pierna borrego', (select id from especies where codigo='B'), 'principal', false, false),
  ('CB', 'Menudo borrego', (select id from especies where codigo='B'), 'principal', false, false),
  ('DB', 'Borrego especial', (select id from especies where codigo='B'), 'principal', false, false),
  ('AC', 'Pulpa pierna cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('BC', 'Pulpa brazo cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('CC', 'Carne asadero', (select id from especies where codigo='C'), 'principal', false, false),
  ('DC', 'Costilla cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('EC', 'Chuleta cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('FC', 'Grasa cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('GC', 'Cuero cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('HC', 'Hueso cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('IC', 'Lomo falda cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('JC', 'Lomo fino cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('KC', 'Tocino', (select id from especies where codigo='C'), 'principal', false, false),
  ('LC', 'Cerdo entero', (select id from especies where codigo='C'), 'principal', false, false),
  ('LLC', 'Codillo', (select id from especies where codigo='C'), 'principal', false, false),
  ('MC', 'Orejas', (select id from especies where codigo='C'), 'principal', false, false),
  ('MTC', 'Manteca cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('NC', 'Patas cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('OC', 'Rack cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('PC', 'Grasa premium', (select id from especies where codigo='C'), 'principal', false, false),
  ('QC', 'Lechones', (select id from especies where codigo='C'), 'principal', false, false),
  ('RC', 'Cachetes cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('SC', 'Pierna cerdo entera', (select id from especies where codigo='C'), 'principal', false, false),
  ('TC', 'Chanfaina cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('UC', 'Menudo cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('WC', 'Chuleta pierna cortada', (select id from especies where codigo='C'), 'principal', false, false),
  ('XC', 'Triming grasa cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('ZC', 'Bondiola', (select id from especies where codigo='C'), 'principal', false, false),
  ('YC', 'Matambre', (select id from especies where codigo='C'), 'principal', false, false),
  ('VCC', 'Corazón cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('SCB', 'Brazo cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('MPH', 'Mapahuira', (select id from especies where codigo='C'), 'principal', false, false),
  ('PAC', 'Papada cerdo', (select id from especies where codigo='C'), 'principal', false, false),
  ('SGC', 'Sangre cerdo', (select id from especies where codigo='C'), 'merma', false, false),
  ('MRI', 'Bife importado', (select id from especies where codigo='I'), 'principal', false, false),
  ('NRI', 'Picaña importada', (select id from especies where codigo='I'), 'principal', false, false),
  ('TAI', 'Tira de asado importada', (select id from especies where codigo='I'), 'principal', false, false),
  ('DRIBOL', 'Lomo fino importado boliviano', (select id from especies where codigo='I'), 'principal', false, false),
  ('DRIURG', 'Lomo fino uruguayo', (select id from especies where codigo='I'), 'principal', false, false),
  ('AM', 'Albacora', (select id from especies where codigo='M'), 'principal', false, false),
  ('ACNJ', 'Conejo', (select id from especies where codigo='O'), 'principal', false, false),
  ('PTO', 'Pato', (select id from especies where codigo='O'), 'principal', false, false),
  ('QCHL', 'Queso cheddar', (select id from especies where codigo='O'), 'principal', false, false),
  ('QML', 'Queso mozzarella laminado', (select id from especies where codigo='O'), 'principal', false, false),
  ('QMN', 'Queso mozzarella', (select id from especies where codigo='O'), 'principal', false, false),
  ('AV', 'Lenguas', (select id from especies where codigo='V'), 'principal', false, false),
  ('BV', 'Guata', (select id from especies where codigo='V'), 'principal', false, false),
  ('CV', 'Guata precocida', (select id from especies where codigo='V'), 'principal', false, false),
  ('DV', 'Hígado res', (select id from especies where codigo='V'), 'principal', false, false),
  ('FV', 'Riñones', (select id from especies where codigo='V'), 'principal', false, false),
  ('GV', 'Corazón res', (select id from especies where codigo='V'), 'principal', false, false),
  ('HV', 'Criadilla', (select id from especies where codigo='V'), 'principal', false, false),
  ('IV', 'Ubre', (select id from especies where codigo='V'), 'principal', false, false),
  ('JV', 'Chinchulines', (select id from especies where codigo='V'), 'principal', false, false),
  ('KV', 'Librillo', (select id from especies where codigo='V'), 'principal', false, false),
  ('LV', 'Chanfaina res', (select id from especies where codigo='V'), 'principal', false, false),
  ('MV', 'Patas res', (select id from especies where codigo='V'), 'principal', false, false),
  ('YV', 'Cachetes res', (select id from especies where codigo='V'), 'principal', false, false),
  ('ZV', 'Molleja res', (select id from especies where codigo='V'), 'principal', false, false),
  ('NV', 'Pulmón', (select id from especies where codigo='V'), 'principal', false, false),
  ('JVA', 'Chinchulines aliñados', (select id from especies where codigo='V'), 'principal', false, false),
  ('APV', 'Pavo entero', (select id from especies where codigo='PV'), 'principal', false, false),
  ('BPV', 'Pechuga pavo', (select id from especies where codigo='PV'), 'principal', false, false),
  ('AP', 'Pechuga s/p s/h', (select id from especies where codigo='P'), 'principal', false, false),
  ('BP', 'Piernas de pollo', (select id from especies where codigo='P'), 'principal', false, false),
  ('CP', 'Pollo vacío', (select id from especies where codigo='P'), 'principal', false, false),
  ('EP', 'Pechuga entera', (select id from especies where codigo='P'), 'principal', false, false),
  ('FP', '1/4 de pollo', (select id from especies where codigo='P'), 'principal', false, false),
  ('DP', 'Alas de pollo', (select id from especies where codigo='P'), 'principal', false, false),
  ('GP', 'Muslos', (select id from especies where codigo='P'), 'principal', false, false),
  ('IP', 'Menudencia pollo', (select id from especies where codigo='P'), 'principal', false, false),
  ('KPC', 'Gallina de campo', (select id from especies where codigo='P'), 'principal', false, false),
  ('LP', 'Patas pollo', (select id from especies where codigo='P'), 'principal', false, false),
  ('JP', 'Hígado pollo', (select id from especies where codigo='P'), 'principal', false, false),
  ('HP', 'Molleja pollo', (select id from especies where codigo='P'), 'principal', false, false),
  ('HUP', 'Hueso pollo', (select id from especies where codigo='P'), 'subproducto', false, false),
  ('DPA', 'Alas de pollo con espaldilla', (select id from especies where codigo='P'), 'principal', false, false),
  ('AR', 'Pulpa res', (select id from especies where codigo='R'), 'principal', false, false),
  ('AREN', 'Res especial enteras', (select id from especies where codigo='R'), 'principal', false, false),
  ('CR', 'Lomo falda', (select id from especies where codigo='R'), 'principal', false, false),
  ('DR', 'Lomo fino', (select id from especies where codigo='R'), 'principal', false, false),
  ('FR', 'Costilla res', (select id from especies where codigo='R'), 'principal', false, false),
  ('GR', 'Rodaja', (select id from especies where codigo='R'), 'principal', false, false),
  ('HR', 'Hueso res', (select id from especies where codigo='R'), 'principal', false, false),
  ('JR', 'Colita cuadril', (select id from especies where codigo='R'), 'principal', false, false),
  ('KR', 'Hueso blanco', (select id from especies where codigo='R'), 'principal', false, false),
  ('LR', 'Grasa res', (select id from especies where codigo='R'), 'principal', false, false),
  ('MR', 'Bife', (select id from especies where codigo='R'), 'principal', false, false),
  ('NR', 'Picaña', (select id from especies where codigo='R'), 'principal', false, false),
  ('OR', 'Colitas (lomo fino)', (select id from especies where codigo='R'), 'principal', false, false),
  ('PER', 'Brisket especial', (select id from especies where codigo='R'), 'principal', false, false),
  ('PR', 'Lomo aguja / pecho', (select id from especies where codigo='R'), 'principal', false, false),
  ('PRT', 'Lomo aguja / Titán', (select id from especies where codigo='R'), 'principal', false, false),
  ('QR', 'Pulpa brazo / paleta', (select id from especies where codigo='R'), 'principal', false, false),
  ('RR', 'Salón', (select id from especies where codigo='R'), 'principal', false, false),
  ('SR', 'Cuacura', (select id from especies where codigo='R'), 'principal', false, false),
  ('TR', 'Falditas', (select id from especies where codigo='R'), 'principal', false, false),
  ('UR', 'Guagua lomo', (select id from especies where codigo='R'), 'principal', false, false),
  ('VR', 'Colas (rabo vaca)', (select id from especies where codigo='R'), 'principal', false, false),
  ('WR', 'Joroba', (select id from especies where codigo='R'), 'principal', false, false),
  ('XR', 'Grasa pecho', (select id from especies where codigo='R'), 'principal', false, false),
  ('YR', 'Grasa bife', (select id from especies where codigo='R'), 'principal', false, false),
  ('ZR', 'Tira de asado', (select id from especies where codigo='R'), 'principal', false, false),
  ('IR', 'T-bone', (select id from especies where codigo='R'), 'principal', false, false),
  ('IRTWK', 'Tomahawk', (select id from especies where codigo='R'), 'principal', false, false),
  ('CRA', 'Lomo falda limpio', (select id from especies where codigo='R'), 'principal', false, false),
  ('ER', 'Industrial res (corriente)', (select id from especies where codigo='R'), 'subproducto', false, false),
  ('ERAG', 'Industrial Angus', (select id from especies where codigo='R'), 'subproducto', false, false),
  ('ERE', 'Industrial res especial', (select id from especies where codigo='R'), 'subproducto', false, false),
  ('AT', 'Ternera', (select id from especies where codigo='T'), 'principal', false, false),
  ('ARL', 'Pulpa res limpia', (select id from especies where codigo='R'), 'principal', true, false),
  ('ARF', 'Pulpa res para filetear', (select id from especies where codigo='R'), 'principal', true, false),
  ('FLR', 'Filete de res', (select id from especies where codigo='R'), 'principal', true, false),
  ('GCR', 'Goulash corriente', (select id from especies where codigo='R'), 'subproducto', true, false),
  ('GER', 'Goulash especial', (select id from especies where codigo='R'), 'subproducto', true, false),
  ('EMC', 'Molida corriente', (select id from especies where codigo='R'), 'principal', true, false),
  ('EME', 'Molida especial', (select id from especies where codigo='R'), 'principal', true, false),
  ('VNR', 'Venas', (select id from especies where codigo='R'), 'merma', true, false),
  ('SGR', 'Sangre / pérdida en mesa', (select id from especies where codigo='R'), 'merma', true, false),
  ('DSP', 'Desperdicio', (select id from especies where codigo='R'), 'merma', true, false);
